
# эта настройка фреймворка конфигурирует Spring и убирает лог при запуске
spring:

  main:
    log-startup-info: false
    # banner-mode.spring-quiz: off - Эта настройка отключает баннер Spring при запуске
  output.ansi.enabled: ALWAYS
  # Эта настройка устанавливает цвет баннера указанный в файле banner
  # Она должна быть на одном уровне с main

  title: "Тест по Spring Framework"

  # spring-quiz.report — настройки отчёта
  report:
    # spring-quiz.report.enabled — нужно ли формировать отчёт
    enabled: false
    # spring-quiz.report.mode — режим формирования отчёта;
    # может иметь одно из двух значений:
    # verbose — формировать расширенный отчёт
    # concise — формировать сокращённый отчёт
    mode: "concise"
    # spring-quiz.report.output — настройки вывода отчёта
    output:
      # spring-quiz.report.output.mode — режим вывода отчёта;
      # может иметь одно из двух значений:
      # console — вывод отчёта в консоль
      # file — вывод отчёта в файл
      mode: "console"
      # spring-quiz.report.output.path — путь к файлу,
      # в который необходимо записать данные отчёта
      path: "./quiz-result.txt"