CREATE TABLE IF NOT EXISTS FILMS
(
    FILM_ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(300) NOT NULL,
    DESCRIPTION VARCHAR(300) NOT NULL,
    RELEASE DATE,
    DURATION INT,
    MPA_ID INT NOT NULL

);

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(300) NOT NULL UNIQUE,
    LOGIN VARCHAR(300) NOT NULL,
    NAME VARCHAR(300),
    BIRTHDAY DATE
);

CREATE TABLE IF NOT EXISTS FILMUSERLIKES
(
    FILM_ID LONG NOT NULL,
    USER_ID LONG NOT NULL,
    CONSTRAINT "FILMUSERLIKES_PK" PRIMARY KEY (FILM_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS GENRE
(
    GENRE_ID INT PRIMARY KEY AUTO_INCREMENT,
    GENRE_NAME VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILM_GENRE
(
    FILM_ID LONG NOT NULL,
    GENRE_ID INT NOT NULL,
    FOREIGN KEY (FILM_ID) REFERENCES FILMS (FILM_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRE (GENRE_ID)
);


CREATE TABLE IF NOT EXISTS MPA
(
    MPA_ID INT PRIMARY KEY AUTO_INCREMENT,
    MPA_NAME VARCHAR(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
    USER_ID LONG NOT NULL REFERENCES USERS (USER_ID),
    FRIEND_ID LONG NOT NULL
);



















